### ISSUE TITLE
[Bug]: Issues with empty firestore document entries

### ISSUE THREAD

**Issue by flashsturz** [AsifArmanRahman/firebase-rest-api#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
-   OS: Win11
-   Python:3.9.16
```

### What happened?

When fetching data from firestore, the get() function seems to no be dealing well with empty fields in the documents.

An earlier bug report fixed an issue for some of the datatypes (see https://github.com/AsifArmanRahman/firebase-rest-api/issues/7).

In addition to the changes made to resolve the issue in the bug report linked above, I propose the following changes:

**_utils.py**
---
Replace
```python
        elif value.get('stringValue'):
```
```python
	elif value.get('stringValue') is not None:
```

Replace
```python
if val.get('mapValue'):
         data_to_restructure[key] = _from_datastore(val['mapValue'])
```
with
```python
if isinstance(val.get('mapValue'), dict):
	dic = {}

	if val['mapValue'].get('fields'):
		for field_key, field_val in val['mapValue']['fields'].items():
			dic[field_key] = _decode_datastore(field_val)
```

This prevents the software from crashing if our documents contain empty strings ('') or empty dicts ({}) as those were previously not detected and handled correctly.

### Code Snippet

```shell
#This should be enough to trigger the failure if you try to fetch the document:

        data = {
            "configFile": 100002
            + "/config_files/"
            + config.json,
            "Files": [
                100002 + "/files/" + storage_file.txt
            ],
            "userId": 100002,
            "text": "",
            "failure_dict": {},
        }
```

### Anything else?

P.S.: Thanks for this great library!

**Comment by AsifArmanRahman** [comment]
Hey man, apologies for late review. I'll check the issue and the PR as well.

Thanks for your contribution and using this library!

**Comment by AsifArmanRahman** [comment]
> ```shell
>         data = {
>             "configFile": 100002
>             + "/config_files/"
>             + config.json,
>             "Files": [
>                 100002 + "/files/" + storage_file.txt
>             ],
>             "userId": 100002,
>             "text": "",
>             "failure_dict": {},
>         }
> ```

Hello @flashsturz could you please explain this dict data? what is represented by `config.json` and `storage_file.txt`? What kind of object are they?

<br>


Also, this part alone should throw a type error on its own.

```python

>>> data = { 'configFile': 100002 + "/config_files/"}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by flashsturz** [comment]
Seems like I tried to oversimplify the data structure to reproduce the issue.
Below you can see a (obfuscated) structure of the firestore document data (as stored in the variable `data_to_restructure`), which is used in the `_from_datastore` method. This is an except of actual data returned from firestore when fetching one of my documents using the `get()` method.

```bash
{
'fileHashes': {'arrayValue': {'values': [{'stringValue': '637befe8fa5e6ee240ecde19b187c6525a74a8a69a0c2fcecd616ae33f12b592'}]}}, 
'author': {'stringValue': 'test@gmail.com'},
'roles': {'mapValue': {'fields': {'4xyz0390f': {'stringValue': 'owner'}}}},
'rating': {'stringValue': ''},
'description': {'stringValue': ''},
'title': {'stringValue': 'test_Part 0'},
'userId': {'stringValue': '4xyz0390f'},
'subtitle': {'stringValue': ''},
'fileUrl': {'stringValue': '4xyz0390f/storage_folder/042lD61qCByWFv6xgxLW/test_Part 0.json'},
'text': {'stringValue': ''},
'id': {'stringValue': '042lD61qCByWFv6xgxLW'},
'categories': {'arrayValue': {'values': [{'stringValue': 'other'}]}},
'additionalResources': {'mapValue': {}},
'key': {'stringValue': 'test_Part 0.json'},
'timestamp': {'timestampValue': '2023-04-05T10:35:45.442224Z'}
}
```
There are various empty entries of strings, as well as dicts, which cause the `_from_datastore` method to fail.

The `.json` files contain additional information which we want to display to the user, and those files are stored in firebase storage and accessible through the link stored in the firestore document data.
Similarly, we can have links to other files in firebase storage in our firestore document.
