### ISSUE TITLE
[Feature]: email verification redirect url

### ISSUE THREAD

**Issue by AGronowski** [AsifArmanRahman/firebase-rest-api#17]
### Is your proposal related to a problem?

With the `auth.send_email_verification(user['idToken'])` is it possible to specify the url the user will be sent to after clicking the verification link? Now the link goes to a page that says Your email has been verified.

### Describe the solution you'd like.

Have a way to choose the url the user is sent to after clicking the link so they can be redirected back to the app.

**Comment by AsifArmanRahman** [comment]
I don't think firebase has any feature/option like the one you're requesting for. This library only uses the REST API available by Firebase and makes it a python compatible library.
