### ISSUE TITLE
[Bug]: <AttributeError: module 'firebase' has no attribute 'initialize_app'>

### ISSUE THREAD

**Issue by Pereirafarm** [AsifArmanRahman/firebase-rest-api#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
-   OS :Windows 11 Pro for Workstations 21H2
-   Python: 3.11
```

### What happened?

it was running but it stopped working!

### Code Snippet

```shell
import firebase

config = {
    'apiKey': "*****",
    'authDomain': "*****",
    'databaseURL': "*****",
    'projectId': "*****",
    'storageBucket': "*****",
    'messagingSenderId': "*****",
    'appId': "*****",
    'measurementId': "*****"
    }
app = firebase.initialize_app(config)

ler_usuario(self)
db=app.database
usuario=db.get()
for usuario in usuario.each()['user']==[self.root.email_textfield.text]:
    print (usuario.value()['id-lbx'])
```

**Comment by AsifArmanRahman** [comment]
> it was running but it stopped working!

Did you create any folder/python file named firebase in your project directory? It could be due to that otherwise maybe a misconfiguration of a virtual environment.

**Comment by Pereirafarm** [comment]
There is no file named "firebase" in the directory, I have not set up a virtual environment, maybe I should do that. I'll try and let you know.

**Comment by AsifArmanRahman** [comment]
Please provide the error log if it occurs again with venv.

**Comment by Pereirafarm** [comment]
Inside the .venv folder the function worked again
